---
title: "R Notebook"
output: html_notebook
---

```{r}
df_U1<-read.csv("/Users/kiyopippi/Desktop/卒業研究/データ/df_U1.csv")
#label1<-df1[,"label"] #ラベルを抽出
df_U1<-df_U1[,colnames(df_U1) != "X"] #インデックスを取り除く
df_U1[is.na(df_U1)] <- 0 #null埋め
#df1<-df1[,colnames(df1) != "label"] #ラベルを取り除く
df_U1
```


```{r}
library(densityClust)
df_U1_dist<-dist(df_U1)
df_U1_clust<-densityClust(df_U1_dist,gaussian=TRUE)
plot(df_U1_clust)
plotDensityClust(df_U1_clust,type="all")
```
```{r}
df_U1_clust<-findClusters(df_U1_clust,rho=17.5,delta=1.75)
plotDensityClust(df_U1_clust)
```


```{r}
split(df_U1,df_U1_clust$clusters)
```
```{r}
df_U1_clust_result<-split(df_U1,df_U1_clust$clusters)
df_U1_clust_result_1<-df_U1_clust_result$"1"
df_U1_clust_result_2<-df_U1_clust_result$"2"
# df1_clust_result_3<-df1_clust_result$"3"
df_U1_clust_result_1[,"label"]<-0
df_U1_clust_result_2[,"label"]<-1
# df1_clust_result_3[,"label"]<-2
df_U1_clust_final<-rbind(df_U1_clust_result_1,df_U1_clust_result_2)
```


```{r}
index<-as.integer(rownames(df_U1_clust_final))#インデックスをint型に変換
df_U1_clust_final$index<-index
```


```{r}
df_U1_clust_final<-dplyr::select(df_U1_clust_final,index,everything())
df_U1_clust_final<-df_U1_clust_final[order(df_U1_clust_final$index),]
df_U1_clust_final
```


```{r}
clust_label<-df_U1_clust_final[,"label"] #クラスタリングで出たラベルを格納
#df1[,"label"]<-label1
df_U1[,"clust_label"]<-clust_label
df_U1
```
```{r}
write.csv(df_U1, file ="/Users/kiyopippi/Desktop/卒業研究/データ/df_U1_clustering_result.csv")

```




